# EmailAlert Docker Compose ARM版本 (Mac M1/M2)
# 专为Mac Apple Silicon优化

# 扩展配置模板
x-common-variables: &common-variables
  TZ: Asia/Shanghai
  LANG: zh_CN.UTF-8
  LC_ALL: zh_CN.UTF-8

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 30s

services:
  # 后端服务
  backend:
    image: crpi-0vtsukduyebtna5k.cn-hangzhou.personal.cr.aliyuncs.com/willnight/emailalert:backend-arm-latest
    container_name: emailalert-backend
    restart: unless-stopped
    environment:
      <<: *common-variables
      GIN_MODE: release
      PORT: 8080
      DB_PATH: /app/data/emailalert.db
    volumes:
      - backend-data:/app/data
      - backend-logs:/app/logs
    ports:
      - "8080:8080"  # 可选：如果需要直接访问后端API
    networks:
      - emailalert-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O-", "http://localhost:8080/health"]
      <<: *healthcheck-defaults
      retries: 5
      start_period: 40s
    logging: *default-logging
    # Mac ARM优化配置
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'

  # 前端服务 (nginx)
  frontend:
    image: crpi-0vtsukduyebtna5k.cn-hangzhou.personal.cr.aliyuncs.com/willnight/emailalert:frontend-arm-latest
    container_name: emailalert-frontend
    restart: unless-stopped
    environment:
      <<: *common-variables
    ports:
      - "3000:80"  # 映射到宿主机的3000端口
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - emailalert-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      <<: *healthcheck-defaults
      start_period: 10s
    logging: *default-logging
    # Mac ARM优化配置
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=20m
      - /var/cache/nginx:noexec,nosuid,size=20m
      - /var/run:noexec,nosuid,size=10m
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.5'

# 数据卷配置 (Mac ARM优化)
volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/data
  backend-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/logs

# 网络配置 (Mac ARM优化)
networks:
  emailalert-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    driver_opts:
      com.docker.network.bridge.name: emailalert0
      com.docker.network.driver.mtu: 1500
      # Mac ARM网络优化
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.enable_icc: "true" 